###Get user tasks
GET   http://localhost:3000/users/preferences
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNzQwNjUzNjc3fQ.Ui3Y0a07iKRbPXPRiepXgok7dZBdSbHU5NNNVL6U0_4